name: Build Widget
on:
  push:
    tags:
      - 'v*'

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.3.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Create zip file
        run: |
          mkdir -p release
          zip -r release/relay-widget-build.zip ./dist
      
      - name: Get previous tag
        id: get_previous_tag
        run: |
          # List all tags, sort them in reverse version order, and get the second latest
          echo "Listing all tags..."
          git ls-remote --tags --ref --sort='version:refname'
          echo "Listing done."

          # Get the sorted tags and capture the second latest one
          FOUND_TAG=$(git ls-remote --tags --ref --sort='version:refname' | tail -n 2 | head -n 1 | awk -F/ '{print $NF}')

          # Debug output to check if a tag was found
          if [[ -z "$FOUND_TAG" ]]; then
            echo "No previous tag found."
          else
            echo "Previous tag found: ${FOUND_TAG}"
          fi

          # Set the previous tag as an output if found
          echo "previous_tag=$FOUND_TAG" >> $GITHUB_OUTPUT

      # Step 7: Create a GitHub release
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          fail_on_unmatched_files: true
          body: |
            ## What's Changed
            **Full Changelog:** [${{ steps.get_previous_tag.outputs.previous_tag }}..${{ github.ref_name }}](https://github.com/${{ github.repository }}/compare/${{ steps.get_previous_tag.outputs.previous_tag }}...${{ github.ref_name }})
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 8: Upload the build artifact to the release
      - name: Upload artifact to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/relay-widget-build.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}